### ISSUE TITLE
브랜치 네임 변경 필요

### ISSUE THREAD

**Issue by gent0807** [LANTOBOY/EightBitFrontend#9]
지훈님 로컬 브랜친 frontend-test를 seopseop_pr-test로 이름을 변경하고 원격 브랜치도 seopseop_pr-test로 이름을 변경해주세요.
다음의 명령을 8비트 프로젝트 경로 이동한 다음 입력해주세요.
git switch frontend-test
git branch -m seopseop_pr-test
 git push origin -u seopseop_pr-test

**Comment by LANTOBOY** [comment]
알겠습니다!

**Comment by gent0807** [comment]
git push origin --delete frontend-test: 원격 브랜치 삭제
